version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: locasian-mysql
    restart: unless-stopped

    environment:
      # must match application.properties
      MYSQL_DATABASE: locasianusers
      MYSQL_ROOT_PASSWORD: jkf31

    ports:
      - "3307:3306"

    volumes:
      - db_data:/var/lib/mysql

    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  db_data: